// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"testing"
)

func TestAppend_Execute(t *testing.T) {

	parent := &AccessList{}
	cmd := parent.NewAppend()

	called := false
	cmd.CommandAction = func(c *Append) error {
		called = true
		return nil
	}

	args := []string{}
	args = append(args, "--fromFile")
	args = append(args, "test")

	err := cmd.Execute(args)
	if err != nil {
		t.Errorf("Unexpected error: %v", err)
	}
	if !called {
		t.Error("CommandAction was not called")
	}

	if cmd.fromFile != "test" {
		t.Errorf("Expected fromFile to be 'test', got '%v'", cmd.fromFile)
	}
}
