// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"testing"
)

func TestChange_Execute(t *testing.T) {

	parent := &Message{}
	cmd := parent.NewChange()

	called := false
	cmd.CommandAction = func(c *Change) error {
		called = true
		return nil
	}

	args := []string{}
	args = append(args, "--revision")
	args = append(args, "test")
	args = append(args, "--message")
	args = append(args, "test")

	err := cmd.Execute(args)
	if err != nil {
		t.Errorf("Unexpected error: %v", err)
	}
	if !called {
		t.Error("CommandAction was not called")
	}

	if cmd.revision != "test" {
		t.Errorf("Expected revision to be 'test', got '%v'", cmd.revision)
	}
	if cmd.message != "test" {
		t.Errorf("Expected message to be 'test', got '%v'", cmd.message)
	}
}
