// Generated by github.com/arran4/go-subcommand/cmd/gosubc

package main

import (
	"flag"
	"fmt"
	"os"
	"strings"

	"errors"
	"github.com/arran4/golang-rcs/cmd"
	"github.com/arran4/golang-rcs/internal/cli"
)

var _ Cmd = (*Ci)(nil)

type Ci struct {
	*RootCmd
	Flags         *flag.FlagSet
	revision      string
	lockRevision  string
	unlockRev     string
	forceRev      string
	lockSet       bool
	unlockSet     bool
	forceSet      bool
	quiet         bool
	user          string
	message       string
	state         string
	date          string
	zone          string
	files         []string
	SubCommands   map[string]Cmd
	CommandAction func(c *Ci) error
}

type UsageDataCi struct {
	*Ci
	Recursive bool
}

func (c *Ci) Usage() {
	err := executeUsage(os.Stderr, "ci_usage.txt", UsageDataCi{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Ci) UsageRecursive() {
	err := executeUsage(os.Stderr, "ci_usage.txt", UsageDataCi{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Ci) Execute(args []string) error {
	if len(args) > 0 {
		if cmd, ok := c.SubCommands[args[0]]; ok {
			return cmd.Execute(args[1:])
		}
	}
	remainingArgs := make([]string, 0, len(args))
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			remainingArgs = append(remainingArgs, args[i+1:]...)
			break
		}
		if strings.HasPrefix(arg, "-") && arg != "-" {
			name := arg
			value := ""
			hasValue := false
			if strings.Contains(arg, "=") {
				parts := strings.SplitN(arg, "=", 2)
				name = parts[0]
				value = parts[1]
				hasValue = true
			}
			trimmed := strings.TrimLeft(name, "-")
			switch {
			case trimmed == "help" || trimmed == "h":
				c.Usage()
				return nil
			case trimmed == "q":
				c.quiet = true
			case trimmed == "i":
				// Initial checkin — auto-detected by CLI, accept and continue.
			case trimmed == "w" || strings.HasPrefix(trimmed, "w"):
				if trimmed == "w" {
					if !hasValue && i+1 < len(args) && !strings.HasPrefix(args[i+1], "-") {
						c.user = args[i+1]
						i++
						continue
					}
					c.user = value
				} else {
					c.user = strings.TrimPrefix(trimmed, "w")
				}
			case trimmed == "m" || strings.HasPrefix(trimmed, "m"):
				if trimmed == "m" {
					if !hasValue {
						if i+1 < len(args) {
							value = args[i+1]
							i++
						} else {
							return fmt.Errorf("flag -m requires a value")
						}
					}
					c.message = value
				} else {
					c.message = strings.TrimPrefix(trimmed, "m")
				}
			case trimmed == "s" || strings.HasPrefix(trimmed, "s"):
				if trimmed == "s" {
					if !hasValue {
						if i+1 < len(args) {
							value = args[i+1]
							i++
						} else {
							return fmt.Errorf("flag -s requires a value")
						}
					}
					c.state = value
				} else {
					c.state = strings.TrimPrefix(trimmed, "s")
				}
			case trimmed == "d" || strings.HasPrefix(trimmed, "d"):
				if trimmed == "d" {
					if !hasValue {
						if i+1 < len(args) {
							value = args[i+1]
							i++
						} else {
							return fmt.Errorf("flag -d requires a value")
						}
					}
					c.date = value
				} else {
					c.date = strings.TrimPrefix(trimmed, "d")
				}
			case trimmed == "z" || strings.HasPrefix(trimmed, "z"):
				if trimmed == "z" {
					if !hasValue && i+1 < len(args) && !strings.HasPrefix(args[i+1], "-") {
						c.zone = args[i+1]
						i++
						continue
					}
					c.zone = value
				} else {
					c.zone = strings.TrimPrefix(trimmed, "z")
				}
			case trimmed == "r" || strings.HasPrefix(trimmed, "r"):
				if trimmed == "r" {
					if !hasValue {
						if i+1 < len(args) {
							value = args[i+1]
							i++
						} else {
							return fmt.Errorf("flag -r requires a value")
						}
					}
					c.revision = value
				} else {
					c.revision = strings.TrimPrefix(trimmed, "r")
				}
			case trimmed == "l" || strings.HasPrefix(trimmed, "l"):
				c.lockSet = true
				if trimmed == "l" {
					if hasValue {
						c.lockRevision = value
					}
				} else {
					c.lockRevision = strings.TrimPrefix(trimmed, "l")
				}
			case trimmed == "u" || strings.HasPrefix(trimmed, "u"):
				c.unlockSet = true
				if trimmed == "u" {
					if hasValue {
						c.unlockRev = value
					}
				} else {
					c.unlockRev = strings.TrimPrefix(trimmed, "u")
				}
			case trimmed == "f" || strings.HasPrefix(trimmed, "f"):
				c.forceSet = true
				if trimmed == "f" {
					if hasValue {
						c.forceRev = value
					}
				} else {
					c.forceRev = strings.TrimPrefix(trimmed, "f")
				}
			default:
				return fmt.Errorf("unknown flag: %s", name)
			}
			continue
		}
		remainingArgs = append(remainingArgs, arg)
	}
	c.files = remainingArgs

	if c.CommandAction != nil {
		if err := c.CommandAction(c); err != nil {
			return fmt.Errorf("ci failed: %w", err)
		}
		return nil
	}
	c.Usage()
	return nil
}

func (c *RootCmd) NewCi() *Ci {
	set := flag.NewFlagSet("ci", flag.ContinueOnError)
	v := &Ci{RootCmd: c, Flags: set, SubCommands: make(map[string]Cmd)}
	set.Usage = v.Usage
	v.CommandAction = func(c *Ci) error {
		// Reject conflicting lock flags.
		if c.lockSet && c.unlockSet {
			return fmt.Errorf("cannot specify both -l and -u")
		}

		// Reject conflicting revision sources.
		var revSources []string
		if c.revision != "" {
			revSources = append(revSources, "-r")
		}
		if c.lockRevision != "" {
			revSources = append(revSources, "-l")
		}
		if c.unlockRev != "" {
			revSources = append(revSources, "-u")
		}
		if c.forceRev != "" {
			revSources = append(revSources, "-f")
		}
		if len(revSources) > 1 {
			return fmt.Errorf("cannot specify revision in multiple flags: %s", strings.Join(revSources, ", "))
		}

		// Resolve revision from the flag that provided it.
		checkinRevision := c.revision
		disposition := cli.CiRemove
		switch {
		case c.lockSet:
			disposition = cli.CiLock
			if c.lockRevision != "" {
				checkinRevision = c.lockRevision
			}
		case c.unlockSet:
			disposition = cli.CiUnlock
			if c.unlockRev != "" {
				checkinRevision = c.unlockRev
			}
		}
		if c.forceRev != "" {
			checkinRevision = c.forceRev
		}
		err := cli.Ci(checkinRevision, disposition, c.user, c.quiet,
			c.message, c.forceSet, c.state, c.date, c.zone, c.files...)
		if err != nil {
			if errors.Is(err, cmd.ErrPrintHelp) {
				c.Usage()
				return nil
			}
			if errors.Is(err, cmd.ErrHelp) {
				fmt.Fprintf(os.Stderr, "Use '%s help' for more information.\n", os.Args[0])
				return nil
			}
			return err
		}
		return nil
	}
	v.SubCommands["help"] = &InternalCommand{Exec: func(args []string) error { v.Usage(); return nil }, UsageFunc: v.Usage}
	v.SubCommands["usage"] = &InternalCommand{Exec: func(args []string) error { v.Usage(); return nil }, UsageFunc: v.Usage}
	return v
}
