// Generated by github.com/arran4/go-subcommand/cmd/gosubc

package main

import (
	"flag"
	"fmt"
	"os"
	"strings"

	"errors"
	"github.com/arran4/golang-rcs/cmd"
	"github.com/arran4/golang-rcs/internal/cli"
)

// TODO manual fix pending go-subcommand v0.0.21 or greater

var _ Cmd = (*Co)(nil)

type Co struct {
	*RootCmd
	Flags         *flag.FlagSet
	revision      string
	lockRevision  string
	unlockRev     string
	lockSet       bool
	unlockSet     bool
	quiet         bool
	user          string
	files         []string
	SubCommands   map[string]Cmd
	CommandAction func(c *Co) error
}

type UsageDataCo struct {
	*Co
	Recursive bool
}

func (c *Co) Usage() {
	err := executeUsage(os.Stderr, "co_usage.txt", UsageDataCo{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Co) UsageRecursive() {
	err := executeUsage(os.Stderr, "co_usage.txt", UsageDataCo{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Co) Execute(args []string) error {
	if len(args) > 0 {
		if cmd, ok := c.SubCommands[args[0]]; ok {
			return cmd.Execute(args[1:])
		}
	}
	remainingArgs := make([]string, 0, len(args))
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			remainingArgs = append(remainingArgs, args[i+1:]...)
			break
		}
		if strings.HasPrefix(arg, "-") && arg != "-" {
			name := arg
			value := ""
			hasValue := false
			if strings.Contains(arg, "=") {
				parts := strings.SplitN(arg, "=", 2)
				name = parts[0]
				value = parts[1]
				hasValue = true
			}
			trimmed := strings.TrimLeft(name, "-")
			switch {
			case trimmed == "help" || trimmed == "h":
				c.Usage()
				return nil
			case trimmed == "q":
				c.quiet = true
			case trimmed == "w" || strings.HasPrefix(trimmed, "w"):
				if trimmed == "w" {
					if !hasValue && i+1 < len(args) && !strings.HasPrefix(args[i+1], "-") {
						c.user = args[i+1]
						i++
						continue
					}
					c.user = value
				} else {
					c.user = strings.TrimPrefix(trimmed, "w")
				}
			case trimmed == "r" || strings.HasPrefix(trimmed, "r"):
				if trimmed == "r" {
					if !hasValue {
						if i+1 < len(args) {
							value = args[i+1]
							i++
						} else {
							return fmt.Errorf("flag -r requires a value")
						}
					}
					c.revision = value
				} else {
					c.revision = strings.TrimPrefix(trimmed, "r")
				}
			case trimmed == "l" || strings.HasPrefix(trimmed, "l"):
				c.lockSet = true
				if trimmed == "l" {
					if hasValue {
						c.lockRevision = value
					}
				} else {
					c.lockRevision = strings.TrimPrefix(trimmed, "l")
				}
			case trimmed == "u" || strings.HasPrefix(trimmed, "u"):
				c.unlockSet = true
				if trimmed == "u" {
					if hasValue {
						c.unlockRev = value
					}
				} else {
					c.unlockRev = strings.TrimPrefix(trimmed, "u")
				}
			default:
				return fmt.Errorf("unknown flag: %s", name)
			}
			continue
		}
		remainingArgs = append(remainingArgs, arg)
	}
	c.files = remainingArgs

	if c.CommandAction != nil {
		if err := c.CommandAction(c); err != nil {
			return fmt.Errorf("co failed: %w", err)
		}
		return nil
	}
	c.Usage()
	return nil
}

func (c *RootCmd) NewCo() *Co {
	set := flag.NewFlagSet("co", flag.ContinueOnError)
	v := &Co{RootCmd: c, Flags: set, SubCommands: make(map[string]Cmd)}
	set.Usage = v.Usage
	v.CommandAction = func(c *Co) error {
		checkoutRevision := c.revision
		checkoutLock := false
		checkoutUnlock := false
		switch {
		case c.lockSet:
			checkoutLock = true
			checkoutRevision = c.lockRevision
		case c.unlockSet:
			checkoutUnlock = true
			checkoutRevision = c.unlockRev
		}
		if c.revision != "" && (checkoutLock || checkoutUnlock) {
			return fmt.Errorf("cannot combine -r with -l/-u")
		}
		err := cli.Co(checkoutRevision, checkoutLock, checkoutUnlock, c.user, c.quiet, c.files...)
		if err != nil {
			if errors.Is(err, cmd.ErrPrintHelp) {
				c.Usage()
				return nil
			}
			if errors.Is(err, cmd.ErrHelp) {
				fmt.Fprintf(os.Stderr, "Use '%s help' for more information.\n", os.Args[0])
				return nil
			}
			return err
		}
		return nil
	}
	v.SubCommands["help"] = &InternalCommand{Exec: func(args []string) error { v.Usage(); return nil }, UsageFunc: v.Usage}
	v.SubCommands["usage"] = &InternalCommand{Exec: func(args []string) error { v.Usage(); return nil }, UsageFunc: v.Usage}
	return v
}
