// Generated by github.com/arran4/go-subcommand/cmd/gosubc

package main

import (
	"testing"
)

func TestCo_Execute(t *testing.T) {
	parent := &RootCmd{FlagSet: flag.NewFlagSet("root", flag.ContinueOnError), Commands: map[string]Cmd{}}
	cmd := parent.NewCo()

	called := false
	cmd.CommandAction = func(c *Co) error {
		called = true
		if !c.quiet {
			t.Fatalf("quiet flag not parsed")
		}
		if c.lockRevision != "1.1" {
			t.Fatalf("lock revision = %q, want 1.1", c.lockRevision)
		}
		if len(c.files) != 1 || c.files[0] != "input.txt" {
			t.Fatalf("files = %v", c.files)
		}
		return nil
	}

	if err := cmd.Execute([]string{"-q", "-l1.1", "input.txt"}); err != nil {
		t.Fatalf("Execute() error = %v", err)
	}
	if !called {
		t.Fatal("command action not called")
	}
}
