// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"testing"
)

func TestFromMarkdown_Execute(t *testing.T) {

	parent := &RootCmd{
		FlagSet:  flag.NewFlagSet("root", flag.ContinueOnError),
		Commands: make(map[string]Cmd),
	}
	cmd := parent.NewFromMarkdown()

	called := false
	cmd.CommandAction = func(c *FromMarkdown) error {
		called = true
		return nil
	}

	args := []string{}
	args = append(args, "--output")
	args = append(args, "test")
	args = append(args, "--force")
	args = append(args, "--useMmap")

	err := cmd.Execute(args)
	if err != nil {
		t.Errorf("Unexpected error: %v", err)
	}
	if !called {
		t.Error("CommandAction was not called")
	}

	if cmd.output != "test" {
		t.Errorf("Expected output to be 'test', got '%v'", cmd.output)
	}
	if cmd.force != true {
		t.Errorf("Expected force to be true, got '%v'", cmd.force)
	}
	if cmd.useMmap != true {
		t.Errorf("Expected useMmap to be true, got '%v'", cmd.useMmap)
	}
}
