// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"testing"
)

func TestInit_Execute(t *testing.T) {

	parent := &RootCmd{
		FlagSet:  flag.NewFlagSet("root", flag.ContinueOnError),
		Commands: make(map[string]Cmd),
	}
	cmd := parent.NewInit()

	called := false
	cmd.CommandAction = func(c *Init) error {
		called = true
		return nil
	}

	args := []string{}
	args = append(args, "--description")
	args = append(args, "test")

	err := cmd.Execute(args)
	if err != nil {
		t.Errorf("Unexpected error: %v", err)
	}
	if !called {
		t.Error("CommandAction was not called")
	}

	if cmd.description != "test" {
		t.Errorf("Expected description to be 'test', got '%v'", cmd.description)
	}
}
