// Generated by github.com/arran4/go-subcommand/cmd/gosubc

package main

import (
	"flag"
	"fmt"
	"os"
	"strings"

	"errors"
	"github.com/arran4/golang-rcs/cmd"
	"github.com/arran4/golang-rcs/internal/cli"
)

var _ Cmd = (*Init)(nil)

type Init struct {
	*RootCmd
	Flags         *flag.FlagSet
	description   string
	files         []string
	SubCommands   map[string]Cmd
	CommandAction func(c *Init) error
}

type UsageDataInit struct {
	*Init
	Recursive bool
}

func (c *Init) Usage() {
	err := executeUsage(os.Stderr, "init_usage.txt", UsageDataInit{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Init) UsageRecursive() {
	err := executeUsage(os.Stderr, "init_usage.txt", UsageDataInit{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Init) Execute(args []string) error {
	remainingArgs := make([]string, 0, len(args))
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			remainingArgs = append(remainingArgs, args[i+1:]...)
			break
		}
		if strings.HasPrefix(arg, "-") && arg != "-" {
			name := arg
			value := ""
			hasValue := false
			if strings.Contains(arg, "=") {
				parts := strings.SplitN(arg, "=", 2)
				name = parts[0]
				value = parts[1]
				hasValue = true
			}
			trimmed := strings.TrimLeft(name, "-")
			switch {
			case trimmed == "help" || trimmed == "h":
				c.Usage()
				return nil
			case trimmed == "t" || strings.HasPrefix(trimmed, "t"):
				val := ""
				if trimmed == "t" {
					if hasValue {
						val = value
					} else if i+1 < len(args) {
						val = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag -t requires a value")
					}
				} else {
					val = strings.TrimPrefix(trimmed, "t")
				}

				if strings.HasPrefix(val, "-") {
					c.description = strings.TrimPrefix(val, "-")
				} else {
					b, err := os.ReadFile(val)
					if err != nil {
						return fmt.Errorf("read description file %s: %w", val, err)
					}
					c.description = string(b)
				}
			default:
				return fmt.Errorf("unknown flag: %s", name)
			}
			continue
		}
		remainingArgs = append(remainingArgs, arg)
	}
	c.files = remainingArgs

	if c.CommandAction != nil {
		if err := c.CommandAction(c); err != nil {
			return fmt.Errorf("init failed: %w", err)
		}
		return nil
	}
	c.Usage()
	return nil
}

func (c *RootCmd) NewInit() *Init {
	set := flag.NewFlagSet("init", flag.ContinueOnError)
	v := &Init{RootCmd: c, Flags: set, SubCommands: make(map[string]Cmd)}
	set.Usage = v.Usage
	v.CommandAction = func(c *Init) error {
		err := cli.Init(c.description, c.files...)
		if err != nil {
			if errors.Is(err, cmd.ErrPrintHelp) {
				c.Usage()
				return nil
			}
			if errors.Is(err, cmd.ErrHelp) {
				fmt.Fprintf(os.Stderr, "Use '%s help' for more information.\n", os.Args[0])
				return nil
			}
			return err
		}
		return nil
	}
	v.SubCommands["help"] = &InternalCommand{Exec: func(args []string) error { v.Usage(); return nil }, UsageFunc: v.Usage}
	v.SubCommands["usage"] = &InternalCommand{Exec: func(args []string) error { v.Usage(); return nil }, UsageFunc: v.Usage}
	return v
}
