// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"testing"
)

func TestListHeads_Execute(t *testing.T) {

	parent := &RootCmd{
		FlagSet:  flag.NewFlagSet("root", flag.ContinueOnError),
		Commands: make(map[string]Cmd),
	}
	cmd := parent.NewListHeads()

	called := false
	cmd.CommandAction = func(c *ListHeads) error {
		called = true
		return nil
	}

	args := []string{}
	args = append(args, "--useMmap")

	err := cmd.Execute(args)
	if err != nil {
		t.Errorf("Unexpected error: %v", err)
	}
	if !called {
		t.Error("CommandAction was not called")
	}

	if cmd.useMmap != true {
		t.Errorf("Expected useMmap to be true, got '%v'", cmd.useMmap)
	}
}
