// Generated by github.com/arran4/go-subcommand/cmd/gosubc

package main

import (
	"flag"
	"fmt"
	"os"
	"strings"

)

var _ Cmd = (*Locks)(nil)

type Locks struct {
	*RootCmd
	Flags         *flag.FlagSet
	SubCommands   map[string]Cmd
	CommandAction func(c *Locks) error
}

type UsageDataLocks struct {
	*Locks
	Recursive bool
}

func (c *Locks) Usage() {
	err := executeUsage(os.Stderr, "locks_usage.txt", UsageDataLocks{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Locks) UsageRecursive() {
	err := executeUsage(os.Stderr, "locks_usage.txt", UsageDataLocks{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Locks) Execute(args []string) error {
	if len(args) > 0 {
		if cmd, ok := c.SubCommands[args[0]]; ok {
			return cmd.Execute(args[1:])
		}
	}
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			break
		}
		if strings.HasPrefix(arg, "-") && arg != "-" {
			name := arg; value := ""; _ = value;
			trimmedName := strings.TrimLeft(name, "-")
			switch trimmedName {
			case "help", "h":
				c.Usage()
				return nil
			default:
				return fmt.Errorf("unknown flag: %s", name)
			}
		}
	}

	c.Usage()

	return nil
}

func (c *RootCmd) NewLocks() *Locks {
	set := flag.NewFlagSet("locks", flag.ContinueOnError)
	v := &Locks{
		RootCmd:     c,
		Flags:       set,
		SubCommands: make(map[string]Cmd),
	}
	set.Usage = v.Usage

	v.SubCommands["lock-set"] = v.NewLockSet()

	v.SubCommands["remove"] = v.NewRemove()

	v.SubCommands["help"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					v.UsageRecursive()
					return nil
				}
			}
			v.Usage()
			return nil
		},
		UsageFunc: v.Usage,
	}
	v.SubCommands["usage"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					v.UsageRecursive()
					return nil
				}
			}
			v.Usage()
			return nil
		},
		UsageFunc: v.Usage,
	}
	return v
}
