// Generated by github.com/arran4/go-subcommand/cmd/gosubc

package main

import (
	"flag"
	"fmt"
	"os"
	"strings"

	"github.com/arran4/golang-rcs/internal/cli"
)

var _ Cmd = (*Log)(nil)

type Log struct {
	*RootCmd
	Flags         *flag.FlagSet
	SubCommands   map[string]Cmd
	CommandAction func(c *Log) error

	filter       string
	stateFilters []string
	files        []string
}

type UsageDataLog struct {
	*Log
	Recursive bool
}

func (c *Log) Usage() {
	err := executeUsage(os.Stderr, "log_usage.txt", UsageDataLog{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Log) UsageRecursive() {
	err := executeUsage(os.Stderr, "log_usage.txt", UsageDataLog{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Log) Execute(args []string) error {
	if len(args) > 0 {
		if cmd, ok := c.SubCommands[args[0]]; ok {
			return cmd.Execute(args[1:])
		}
	}
	remainingArgs := make([]string, 0, len(args))
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			remainingArgs = append(remainingArgs, args[i+1:]...)
			break
		}
		if strings.HasPrefix(arg, "-") && arg != "-" {
			name := arg
			value := ""
			hasValue := false
			if strings.Contains(arg, "=") {
				parts := strings.SplitN(arg, "=", 2)
				name = parts[0]
				value = parts[1]
				hasValue = true
			}
			trimmed := strings.TrimLeft(name, "-")
			switch {
			case trimmed == "help" || trimmed == "h":
				c.Usage()
				return nil
			case trimmed == "s" || strings.HasPrefix(trimmed, "s"):
				if trimmed == "s" {
					if !hasValue {
						if i+1 < len(args) && !strings.HasPrefix(args[i+1], "-") {
							c.stateFilters = append(c.stateFilters, args[i+1])
							i++
							continue
						}
						return fmt.Errorf("flag -s requires a value")
					}
					c.stateFilters = append(c.stateFilters, value)
				} else {
					val := strings.TrimPrefix(trimmed, "s")
					c.stateFilters = append(c.stateFilters, val)
				}
			case trimmed == "F" || trimmed == "filter":
				if !hasValue {
					if i+1 < len(args) && !strings.HasPrefix(args[i+1], "-") {
						c.filter = args[i+1]
						i++
						continue
					}
					return fmt.Errorf("flag -%s requires a value", trimmed)
				}
				c.filter = value
			default:
				return fmt.Errorf("unknown flag: %s", name)
			}
			continue
		}
		remainingArgs = append(remainingArgs, arg)
	}
	c.files = remainingArgs

	if c.CommandAction != nil {
		return c.CommandAction(c)
	}

	c.Usage()

	return nil
}

func (c *RootCmd) NewLog() *Log {
	set := flag.NewFlagSet("log", flag.ContinueOnError)
	v := &Log{
		RootCmd:     c,
		Flags:       set,
		SubCommands: make(map[string]Cmd),
	}
	set.Usage = v.Usage

	v.CommandAction = func(c *Log) error {
		return cli.Log(c.filter, c.stateFilters, c.files...)
	}

	v.SubCommands["message"] = v.NewMessage()

	v.SubCommands["help"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					v.UsageRecursive()
					return nil
				}
			}
			v.Usage()
			return nil
		},
		UsageFunc: v.Usage,
	}
	v.SubCommands["usage"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					v.UsageRecursive()
					return nil
				}
			}
			v.Usage()
			return nil
		},
		UsageFunc: v.Usage,
	}
	return v
}
