// Generated by github.com/arran4/go-subcommand/cmd/gosubc

package main

import (
	"flag"
	"fmt"
	"os"

	"github.com/arran4/golang-rcs/internal/cli"
)

var _ Cmd = (*LogMessageList)(nil)

type LogMessageList struct {
	*LogMessage
	Flags *flag.FlagSet
	files []string
}

type UsageDataLogMessageList struct {
	*LogMessageList
	Recursive bool
}

func (c *LogMessageList) Usage() {
	// TODO: Create usage template
	fmt.Fprintf(os.Stderr, "Usage of %s log message list:\n", os.Args[0])
	c.Flags.PrintDefaults()
}

func (c *LogMessageList) Execute(args []string) error {
	if err := c.Flags.Parse(args); err != nil {
		return err
	}
	c.files = c.Flags.Args()
	return cli.LogMessageList(c.files...)
}

func (c *LogMessage) NewLogMessageList() *LogMessageList {
	set := flag.NewFlagSet("list", flag.ContinueOnError)
	v := &LogMessageList{
		LogMessage: c,
		Flags:      set,
	}
	set.Usage = v.Usage
	return v
}
