// Generated by github.com/arran4/go-subcommand/cmd/gosubc

package main

import (
	"flag"
	"testing"
)

func TestLog_Execute(t *testing.T) {

	parent := &RootCmd{
		FlagSet:  flag.NewFlagSet("root", flag.ContinueOnError),
		Commands: make(map[string]Cmd),
	}
	cmd := parent.NewLog()

	called := false
	cmd.CommandAction = func(c *Log) error {
		called = true
		return nil
	}

	args := []string{}

	err := cmd.Execute(args)
	if err != nil {
		t.Errorf("Unexpected error: %v", err)
	}
	if !called {
		t.Error("CommandAction was not called")
	}
}
