// Generated by github.com/arran4/go-subcommand/cmd/gosubc

package main

import (
	"flag"
	"fmt"
	"os"
	"strings"
)

var _ Cmd = (*Message)(nil)

type Message struct {
	*Log
	Flags       *flag.FlagSet
	SubCommands map[string]Cmd
}

type UsageDataMessage struct {
	*Message
	Recursive bool
}

func (c *Message) Usage() {
	err := executeUsage(os.Stderr, "message_usage.txt", UsageDataMessage{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Message) UsageRecursive() {
	err := executeUsage(os.Stderr, "message_usage.txt", UsageDataMessage{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Message) Execute(args []string) error {
	if len(args) > 0 {
		if cmd, ok := c.SubCommands[args[0]]; ok {
			return cmd.Execute(args[1:])
		}
	}
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			break
		}
		if strings.HasPrefix(arg, "-") {
			name := arg
			trimmedName := strings.TrimLeft(name, "-")
			switch trimmedName {
			case "help", "h":
				c.Usage()
				return nil
			default:
				return fmt.Errorf("unknown flag: %s", name)
			}
		}
	}

	c.Usage()

	return nil
}

func (c *Log) NewMessage() *Message {
	set := flag.NewFlagSet("message", flag.ContinueOnError)
	v := &Message{
		Log:         c,
		Flags:       set,
		SubCommands: make(map[string]Cmd),
	}
	set.Usage = v.Usage

	v.SubCommands["change"] = v.NewChange()

	v.SubCommands["list"] = v.NewList()

	v.SubCommands["print"] = v.NewPrint()

	v.SubCommands["help"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					v.UsageRecursive()
					return nil
				}
			}
			v.Usage()
			return nil
		},
		UsageFunc: v.Usage,
	}
	v.SubCommands["usage"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					v.UsageRecursive()
					return nil
				}
			}
			v.Usage()
			return nil
		},
		UsageFunc: v.Usage,
	}
	return v
}
