// Generated by github.com/arran4/go-subcommand/cmd/gosubc

package main

import (
	"flag"
	"fmt"
	"os"
	"strconv"
	"strings"

	"errors"
	"github.com/arran4/golang-rcs/cmd"
	"github.com/arran4/golang-rcs/internal/cli"
)

var _ Cmd = (*NormalizeRevisions)(nil)

type NormalizeRevisions struct {
	*RootCmd
	Flags         *flag.FlagSet
	padCommits    bool
	mmap          bool
	files         []string
	SubCommands   map[string]Cmd
	CommandAction func(c *NormalizeRevisions) error
}

type UsageDataNormalizeRevisions struct {
	*NormalizeRevisions
	Recursive bool
}

func (c *NormalizeRevisions) Usage() {
	err := executeUsage(os.Stderr, "normalize-revisions_usage.txt", UsageDataNormalizeRevisions{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *NormalizeRevisions) UsageRecursive() {
	err := executeUsage(os.Stderr, "normalize-revisions_usage.txt", UsageDataNormalizeRevisions{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *NormalizeRevisions) Execute(args []string) error {
	if len(args) > 0 {
		if cmd, ok := c.SubCommands[args[0]]; ok {
			return cmd.Execute(args[1:])
		}
	}
	var remainingArgs []string
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			remainingArgs = append(remainingArgs, args[i+1:]...)
			break
		}
		if strings.HasPrefix(arg, "-") && arg != "-" {
			name := arg
			value := ""
			hasValue := false
			if strings.Contains(arg, "=") {
				parts := strings.SplitN(arg, "=", 2)
				name = parts[0]
				value = parts[1]
				hasValue = true
			}
			trimmedName := strings.TrimLeft(name, "-")
			switch trimmedName {

			case "padCommits", "pad-commits", "p":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.padCommits = b
				} else {
					c.padCommits = true
				}
			case "mmap", "m":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.mmap = b
				} else {
					c.mmap = true
				}
			case "help", "h":
				c.Usage()
				return nil
			default:
				return fmt.Errorf("unknown flag: %s", name)
			}
		} else {
			remainingArgs = append(remainingArgs, arg)
		}
	}
	// Handle vararg files
	{
		varArgStart := 0
		if varArgStart > len(remainingArgs) {
			varArgStart = len(remainingArgs)
		}
		varArgs := remainingArgs[varArgStart:]
		c.files = varArgs
	}

	if c.CommandAction != nil {
		if err := c.CommandAction(c); err != nil {
			return fmt.Errorf("normalize-revisions failed: %w", err)
		}
	} else {
		c.Usage()
	}

	return nil
}

func (c *RootCmd) NewNormalizeRevisions() *NormalizeRevisions {
	set := flag.NewFlagSet("normalize-revisions", flag.ContinueOnError)
	v := &NormalizeRevisions{
		RootCmd:     c,
		Flags:       set,
		SubCommands: make(map[string]Cmd),
	}

	set.BoolVar(&v.padCommits, "pad-commits", false, "pad commits with empty commits")
	set.BoolVar(&v.padCommits, "p", false, "pad commits with empty commits")

	set.BoolVar(&v.mmap, "mmap", false, "Use mmap for reading files")
	set.BoolVar(&v.mmap, "m", false, "Use mmap for reading files")

	set.Usage = v.Usage

	v.CommandAction = func(c *NormalizeRevisions) error {

		err := cli.NormalizeRevisions(c.padCommits, c.mmap || c.Mmap, c.files...)
		if err != nil {
			if errors.Is(err, cmd.ErrPrintHelp) {
				c.Usage()
				return nil
			}
			if errors.Is(err, cmd.ErrHelp) {
				fmt.Fprintf(os.Stderr, "Use '%s help' for more information.\n", os.Args[0])
				return nil
			}
			return fmt.Errorf("normalize-revisions failed: %w", err)
		}
		return nil
	}

	v.SubCommands["help"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					v.UsageRecursive()
					return nil
				}
			}
			v.Usage()
			return nil
		},
		UsageFunc: v.Usage,
	}
	v.SubCommands["usage"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					v.UsageRecursive()
					return nil
				}
			}
			v.Usage()
			return nil
		},
		UsageFunc: v.Usage,
	}
	return v
}
