// Generated by github.com/arran4/go-subcommand/cmd/gosubc

package main

import (
	"flag"
	"fmt"
	"io"
	"os"

	"github.com/arran4/golang-rcs/cmd/gorcs/templates"
)

type Cmd interface {
	Execute(args []string) error
	Usage()
}

type InternalCommand struct {
	Exec      func(args []string) error
	UsageFunc func()
}

func (c *InternalCommand) Execute(args []string) error {
	return c.Exec(args)
}

func (c *InternalCommand) Usage() {
	c.UsageFunc()
}

type UserError struct {
	Err error
	Msg string
}

func (e *UserError) Error() string {
	if e.Err != nil {
		return fmt.Sprintf("%s: %v", e.Msg, e.Err)
	}
	return e.Msg
}

func NewUserError(err error, msg string) *UserError {
	return &UserError{Err: err, Msg: msg}
}

func executeUsage(out io.Writer, templateName string, data interface{}) error {
	return templates.GetTemplates().ExecuteTemplate(out, templateName, data)
}

type RootCmd struct {
	*flag.FlagSet
	Commands      map[string]Cmd
	Version       string
	Commit        string
	Date          string
	CommandAction func(c *RootCmd) error
}

func (c *RootCmd) Usage() {
	fmt.Fprintf(os.Stderr, "Usage of %s:\n", os.Args[0])
	c.PrintDefaults()
	fmt.Fprintln(os.Stderr, "  Commands:")
	for name := range c.Commands {
		fmt.Fprintf(os.Stderr, "    %s\n", name)
	}
}

func (c *RootCmd) UsageRecursive() {
	fmt.Fprintf(os.Stderr, "Usage of %s:\n", os.Args[0])
	c.PrintDefaults()
	fmt.Fprintln(os.Stderr, "  Commands:")
	fmt.Fprintf(os.Stderr, "    %s\n", "access-list")
	fmt.Fprintf(os.Stderr, "    %s\n", "access-list append")
	fmt.Fprintf(os.Stderr, "    %s\n", "access-list copy")
	fmt.Fprintf(os.Stderr, "    %s\n", "branches")
	fmt.Fprintf(os.Stderr, "    %s\n", "branches default")
	fmt.Fprintf(os.Stderr, "    %s\n", "branches default set")
	fmt.Fprintf(os.Stderr, "    %s\n", "format")
	fmt.Fprintf(os.Stderr, "    %s\n", "from-json")
	fmt.Fprintf(os.Stderr, "    %s\n", "from-markdown")
	fmt.Fprintf(os.Stderr, "    %s\n", "init")
	fmt.Fprintf(os.Stderr, "    %s\n", "list-heads")
	fmt.Fprintf(os.Stderr, "    %s\n", "log")
	fmt.Fprintf(os.Stderr, "    %s\n", "log message")
	fmt.Fprintf(os.Stderr, "    %s\n", "log message change")
	fmt.Fprintf(os.Stderr, "    %s\n", "log message list")
	fmt.Fprintf(os.Stderr, "    %s\n", "log message print")
	fmt.Fprintf(os.Stderr, "    %s\n", "normalize-revisions")
	fmt.Fprintf(os.Stderr, "    %s\n", "state")
	fmt.Fprintf(os.Stderr, "    %s\n", "state alter")
	fmt.Fprintf(os.Stderr, "    %s\n", "state get")
	fmt.Fprintf(os.Stderr, "    %s\n", "state ls")
	fmt.Fprintf(os.Stderr, "    %s\n", "to-json")
	fmt.Fprintf(os.Stderr, "    %s\n", "to-markdown")
	fmt.Fprintf(os.Stderr, "    %s\n", "validate")
}

func NewRoot(name, version, commit, date string) (*RootCmd, error) {
	c := &RootCmd{
		FlagSet:  flag.NewFlagSet(name, flag.ExitOnError),
		Commands: make(map[string]Cmd),
		Version:  version,
		Commit:   commit,
		Date:     date,
	}
	c.FlagSet.Usage = c.Usage

	c.Commands["access-list"] = c.NewAccessList()
	c.Commands["branches"] = c.NewBranches()
	c.Commands["format"] = c.NewFormat()
	c.Commands["from-json"] = c.NewFromJson()
	c.Commands["from-markdown"] = c.NewFromMarkdown()
	c.Commands["init"] = c.NewInit()
	c.Commands["list-heads"] = c.NewListHeads()
	c.Commands["log"] = c.NewLog()
	c.Commands["normalize-revisions"] = c.NewNormalizeRevisions()
	c.Commands["state"] = c.NewState()
	c.Commands["to-json"] = c.NewToJson()
	c.Commands["to-markdown"] = c.NewToMarkdown()
	c.Commands["validate"] = c.NewValidate()
	c.Commands["help"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					c.UsageRecursive()
					return nil
				}
			}
			c.Usage()
			return nil
		},
		UsageFunc: c.Usage,
	}
	c.Commands["usage"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					c.UsageRecursive()
					return nil
				}
			}
			c.Usage()
			return nil
		},
		UsageFunc: c.Usage,
	}
	c.Commands["version"] = &InternalCommand{
		Exec: func(args []string) error {
			fmt.Printf("Version: %s\nCommit: %s\nDate: %s\n", c.Version, c.Commit, c.Date)
			return nil
		},
		UsageFunc: func() {
			fmt.Fprintf(os.Stderr, "Usage: %s version\n", os.Args[0])
		},
	}
	return c, nil
}

func (c *RootCmd) Execute(args []string) error {
	if err := c.Parse(args); err != nil {
		return NewUserError(err, fmt.Sprintf("flag parse error %s", err.Error()))
	}
	remainingArgs := c.Args()
	if len(remainingArgs) < 1 {
		c.Usage()
		return nil
	}
	cmd, ok := c.Commands[remainingArgs[0]]
	if !ok {
		c.Usage()
		return fmt.Errorf("unknown command: %s", remainingArgs[0])
	}
	return cmd.Execute(remainingArgs[1:])
}
