// Generated by github.com/arran4/go-subcommand/cmd/gosubc

package main

import (
	"flag"
	"testing"
)

func TestSet_Execute(t *testing.T) {

	parent := &Default{}
	cmd := parent.NewSet()

	called := false
	cmd.CommandAction = func(c *Set) error {
		called = true
		return nil
	}

	args := []string{}

	err := cmd.Execute(args)
	if err != nil {
		t.Errorf("Unexpected error: %v", err)
	}
	if !called {
		t.Error("CommandAction was not called")
	}
}
